name: xstate_fsm
version: 0.0.2
description: >
  A rudimentary copy of XState
  (https://xstate.js.org/)
homepage: https://github.com/Bemaja/xstate-fsm

dependencies:
  equatable: ^2.0.3
  logging: ^1.0.2

dev_dependencies:
  test: ^1.20.0
  stack_trace: ^1.10.0

environment:
  sdk: ">=2.3.0 <3.0.0"

