name: xstate_fsm
version: 0.0.2
description: >
  A rudimentary copy of XState
  (https://xstate.js.org/)
homepage: https://github.com/Bemaja/xstate-fsm

dependencies:
  equatable: ^1.1.1
  logging: ^0.11.4

dev_dependencies:
  test: ^1.14.0
  stack_trace: ^1.9.3

environment:
  sdk: ">=2.3.0 <3.0.0"

